package com.network.snmp.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import com.network.snmp.model.InterfaceMetricDaily;
import com.network.snmp.model.NetworkDetails;
import com.network.snmp.repository.mysql.NetworkDetailsRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.Instant;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class ReportService {

    private final NetworkDetailsRepository networkRepo;
    private final MetricsQueryService queryService;

    public byte[] generateDevicePdf(String systemName) throws DocumentException {
        NetworkDetails device = networkRepo.findBySystemName(systemName)
                .orElseThrow(() -> new RuntimeException("Device not found"));

        List<InterfaceMetricDaily> dailyData = queryService.getDailyMetrics(systemName, 30);

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, out);

        document.open();
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, Color.DARK_GRAY);
        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.WHITE);
        Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.BLACK);

        Paragraph title = new Paragraph("Device Status Report", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);
        document.add(new Paragraph("\n"));

        PdfPTable infoTable = new PdfPTable(2);
        infoTable.setWidthPercentage(100);
        infoTable.setSpacingAfter(20f);

        addInfoRow(infoTable, "System Name:", device.getSystemName());
        addInfoRow(infoTable, "IP Address:", device.getIpAddress());
        addInfoRow(infoTable, "Report Generated:", Instant.now().toString().split("T")[0]);
        addInfoRow(infoTable, "Total Interfaces:", String.valueOf(device.getTotalInterfaces()));
        addInfoRow(infoTable, "Last Scan:", device.getLastScanTime().toString());

        document.add(infoTable);

        PdfPTable table = new PdfPTable(5); // Columns: Index, Name, Type, Usage, Total Volume
        table.setWidthPercentage(100);
        table.setWidths(new float[]{1f, 4f, 2f, 2f, 2f});
        String[] headers = {"ID", "Interface Name", "Type", "Avg Load", "Total Vol"};
        for (String h : headers) {
            PdfPCell cell = new PdfPCell(new Phrase(h, headerFont));
            cell.setBackgroundColor(new Color(66, 133, 244)); // Blue Header
            cell.setPadding(6);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
        }

        var grouped = dailyData.stream().collect(Collectors.groupingBy(InterfaceMetricDaily::getInterfaceIndex));

        grouped.keySet().stream().sorted().forEach(idx -> {
            List<InterfaceMetricDaily> history = grouped.get(idx);
            InterfaceMetricDaily latest = history.get(0);

            long totalVol = history.stream().mapToLong(d -> (d.getTotalRxBytes() != null ? d.getTotalRxBytes() : 0) + (d.getTotalTxBytes() != null ? d.getTotalTxBytes() : 0)).sum();
            double avgRxUtil = history.stream().mapToDouble(d -> d.getAvgRxPercent() != null ? d.getAvgRxPercent() : 0).average().orElse(0);
            double avgTxUtil = history.stream().mapToDouble(d -> d.getAvgTxPercent() != null ? d.getAvgTxPercent() : 0).average().orElse(0);
            double maxUtil = Math.max(avgRxUtil, avgTxUtil);

            if (totalVol > 0) {
                table.addCell(new Phrase(String.valueOf(idx), cellFont));
                table.addCell(new Phrase(latest.getInterfaceName(), cellFont));
                table.addCell(new Phrase(latest.getInterfaceType(), cellFont));

                PdfPCell utilCell = new PdfPCell(new Phrase(String.format("%.1f%%", maxUtil), cellFont));
                if(maxUtil > 80) utilCell.setBackgroundColor(new Color(255, 200, 200)); // Highlight high usage
                table.addCell(utilCell);

                table.addCell(new Phrase(formatBytes(totalVol), cellFont));
            }
        });

        document.add(table);

        // 6. Footer
        Paragraph footer = new Paragraph("\n\nGenerated by SNMP NetMonitor System", FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10, Color.GRAY));
        footer.setAlignment(Element.ALIGN_CENTER);
        document.add(footer);

        document.close();
        return out.toByteArray();
    }

    private void addInfoRow(PdfPTable table, String label, String value) {
        PdfPCell l = new PdfPCell(new Phrase(label, FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10)));
        l.setBorder(Rectangle.NO_BORDER);
        table.addCell(l);

        PdfPCell v = new PdfPCell(new Phrase(value, FontFactory.getFont(FontFactory.HELVETICA, 10)));
        v.setBorder(Rectangle.NO_BORDER);
        table.addCell(v);
    }

    private String formatBytes(long bytes) {
        if (bytes >= 1_000_000_000) return String.format("%.2f GB", bytes / 1.0e9);
        if (bytes >= 1_000_000) return String.format("%.2f MB", bytes / 1.0e6);
        return String.format("%d B", bytes);
    }
}